---
- hosts: all
  become: true
  roles:
    - role: common
      tags: [ common ]

- hosts: terraform
  become: true
  roles:
    - role: terraform
      tags: [ terraform ]
    - role: scaleway_cli
      tags: [ scaleway_cli ]
    